/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/iphone16_mockup/iphone-16-pro.glb --types 
*/

import * as THREE from 'three'
import React, {  useEffect, useRef, Suspense, Component, ReactNode , useMemo } from 'react'
import { useGLTF, useTexture,  Environment, ContactShadows, Html,  Center , Resize} from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import AuroraBackground from '@/components/ui/aurora-background';
import HighlightCard from '@/components/ui/highlight-card';
import { Compass, ArrowRight, Map as MapIcon } from 'lucide-react';
gsap.registerPlugin(ScrollTrigger)


class ErrorBoundary extends Component<{children: ReactNode, fallback: (error: Error) => ReactNode}, {hasError: boolean, error: Error | null}> {
  constructor(props: {children: ReactNode, fallback: (error: Error) => ReactNode}) {
    super(props);
    this.state = { hasError: false, error: null };
  }
  static getDerivedStateFromError(error: Error) {
    return { hasError: true, error };
  }
  render() {
    if (this.state.hasError && this.state.error) {
      return this.props.fallback(this.state.error);
    }
    return this.props.children;
  }
}

type GLTFResult = GLTF & {
  nodes: {
    ['back-camera-lente-1-a']: THREE.Mesh
    ['back-camera-lente-1-b']: THREE.Mesh
    ['back-camera-lente-1-c']: THREE.Mesh
    ['back-camera-lente-1-d']: THREE.Mesh
    ['back-camera-lente-1-n']: THREE.Mesh
    ['back-camera-lente-1-p']: THREE.Mesh
    ['back-camera-lente-1-o']: THREE.Mesh
    ['back-camera-lente-1-l']: THREE.Mesh
    ['back-camera-lente-1-j']: THREE.Mesh
    ['back-camera-lente-1-i']: THREE.Mesh
    ['back-camera-lente-1-h']: THREE.Mesh
    ['back-camera-lente-1-g']: THREE.Mesh
    ['back-camera-lente-1-e']: THREE.Mesh
    ['back-camera-lente-1-f']: THREE.Mesh
    ['back-camera-lente-2-a']: THREE.Mesh
    ['back-camera-lente-2-b']: THREE.Mesh
    ['back-camera-lente-2-d']: THREE.Mesh
    ['back-camera-lente-2-g']: THREE.Mesh
    ['back-camera-lente-2-k']: THREE.Mesh
    ['back-camera-lente-2-l']: THREE.Mesh
    ['back-camera-lente-2-m']: THREE.Mesh
    ['back-camera-lente-2-j']: THREE.Mesh
    ['back-camera-lente-2-i']: THREE.Mesh
    ['back-camera-lente-2-h']: THREE.Mesh
    ['back-camera-lente-2-e']: THREE.Mesh
    ['back-camera-lente-2-f']: THREE.Mesh
    ['back-camera-lente-3-a']: THREE.Mesh
    ['back-camera-lente-3-b']: THREE.Mesh
    ['back-camera-lente-3-c']: THREE.Mesh
    ['back-camera-lente-3-d']: THREE.Mesh
    ['back-camera-lente-3-e']: THREE.Mesh
    ['back-camera-lente-3-f']: THREE.Mesh
    ['back-camera-lente-3-g']: THREE.Mesh
    ['back-camera-lente-3-h']: THREE.Mesh
    ['back-camera-lente-3-i']: THREE.Mesh
    ['back-camera-lente-3-j']: THREE.Mesh
    ['back-camera-lente-3-k']: THREE.Mesh
    ['back-camera-lente-3-l']: THREE.Mesh
    ['back-camera-flash-a']: THREE.Mesh
    ['back-camera-flash-b']: THREE.Mesh
    ['back-camera-flash-c']: THREE.Mesh
    ['back-camera-flash-d']: THREE.Mesh
    ['back-camera-flash-e']: THREE.Mesh
    ['back-camera-flash-f']: THREE.Mesh
    ['back-camera']: THREE.Mesh
    ['back-camera-2']: THREE.Mesh
    ['back-camera-3']: THREE.Mesh
    ['back-camera-4']: THREE.Mesh
    ['frontal-camera-4']: THREE.Mesh
    ['frontal-camera-5']: THREE.Mesh
    ['frontal-camera-6']: THREE.Mesh
    ['frontal-camera-7']: THREE.Mesh
    ['frontal-camera-8']: THREE.Mesh
    ['frontal-camera-9']: THREE.Mesh
    ['frontal-camera-10']: THREE.Mesh
    ['frontal-camera-1']: THREE.Mesh
    ['frontal-camera-2']: THREE.Mesh
    ['edge-a']: THREE.Mesh
    ['edge-b']: THREE.Mesh
    ['button-2']: THREE.Mesh
    ['button-3']: THREE.Mesh
    ['button-4']: THREE.Mesh
    ['button-6']: THREE.Mesh
    ['edge-display']: THREE.Mesh
    ['button-5-center']: THREE.Mesh
    ['button-5']: THREE.Mesh
    ['port-usb-1']: THREE.Mesh
    ['port-usb-2']: THREE.Mesh
    ['port-usb-3']: THREE.Mesh
    ['port-usb-4']: THREE.Mesh
    ['port-usb-5']: THREE.Mesh
    ['port-usb-6']: THREE.Mesh
    ['port-usb-7']: THREE.Mesh
    ['port-usb-9']: THREE.Mesh
    ['port-usb-8']: THREE.Mesh
    ['sepaker-1']: THREE.Mesh
    ['speaker-2']: THREE.Mesh
    ['shadow-1']: THREE.Mesh
    ['shadow-2']: THREE.Mesh
    back: THREE.Mesh
    screws: THREE.Mesh
    ['microphones-lower']: THREE.Mesh
    display: THREE.Mesh
  }
  materials: {
    ['iphone-16-pro-001.001']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model({ imagePath = '/models/iphone16_mockup/screen.jpg', ...props }: any) {
  const { nodes, materials } = (useGLTF(import.meta.env.BASE_URL + 'models/iphone16_mockup/iphone-16-pro.glb') as unknown) as GLTFResult
  const screenTexture = useTexture(imagePath.startsWith('/') ? import.meta.env.BASE_URL + imagePath.slice(1) : imagePath) as THREE.Texture

  // Fix texture orientation if necessary
  screenTexture.flipY = false;


  const darkMat = useMemo(() => {
    const mat = materials['iphone-16-pro-001.001'];
    const clone = mat ? mat.clone() : new THREE.MeshStandardMaterial();
    clone.color.set('#111111');
    clone.roughness = 0.1;
    return clone;
  }, [materials]);
  
  const flashMat = useMemo(() => {
    const mat = materials['iphone-16-pro-001.001'];
    const clone = mat ? mat.clone() : new THREE.MeshStandardMaterial();
    clone.color.set('#ffffee');
    clone.emissive = new THREE.Color('#ffffee');
    return clone;
  }, [materials]);

  useEffect(() => {
    const mat = materials['iphone-16-pro-001.001'];
    if (mat) {
      mat.color.set('#5c5b57'); // Graphite Gray
      mat.metalness = 0.85;
      mat.roughness = 0.25;
      mat.needsUpdate = true;
    }

    // Fix screen UV mapping by applying a planar projection based on its bounding box
    const displayGeo = nodes.display.geometry;
    displayGeo.computeBoundingBox();
    const bbox = displayGeo.boundingBox;
    if (bbox) {
      const pos = displayGeo.attributes.position;
      const uv = displayGeo.attributes.uv;
      if (pos && uv) {
        for (let i = 0; i < pos.count; i++) {
          const x = pos.getX(i);
          const y = pos.getY(i);
          // Normalize coordinates from 0 to 1 across the width and height, and invert to fix mirroring
          const u = 1 - (x - bbox.min.x) / (bbox.max.x - bbox.min.x);
          const v = 1 - (y - bbox.min.y) / (bbox.max.y - bbox.min.y);
          uv.setXY(i, u, v);
        }
        uv.needsUpdate = true;
      }
    }
  }, [materials, nodes]);

  return (
    <group {...props} dispose={null}>
            <mesh geometry={nodes['back-camera-lente-1-a'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-b'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-c'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-d'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-n'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-p'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-o'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-l'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-j'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-i'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-h'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-g'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-e'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-1-f'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-a'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-b'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-d'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-g'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-k'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-l'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-m'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-j'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-i'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-h'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-e'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-2-f'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-a'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-b'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-c'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-d'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-e'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-f'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-g'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-h'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-i'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-j'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-k'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-lente-3-l'].geometry} material={darkMat} />
      <mesh geometry={nodes['back-camera-flash-a'].geometry} material={flashMat} />
      <mesh geometry={nodes['back-camera-flash-b'].geometry} material={flashMat} />
      <mesh geometry={nodes['back-camera-flash-c'].geometry} material={flashMat} />
      <mesh geometry={nodes['back-camera-flash-d'].geometry} material={flashMat} />
      <mesh geometry={nodes['back-camera-flash-e'].geometry} material={flashMat} />
      <mesh geometry={nodes['back-camera-flash-f'].geometry} material={flashMat} />
      <mesh geometry={nodes['back-camera'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['back-camera-2'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['back-camera-3'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['back-camera-4'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['frontal-camera-4'].geometry} material={darkMat} />
      <mesh geometry={nodes['frontal-camera-5'].geometry} material={darkMat} />
      <mesh geometry={nodes['frontal-camera-6'].geometry} material={darkMat} />
      <mesh geometry={nodes['frontal-camera-7'].geometry} material={darkMat} />
      <mesh geometry={nodes['frontal-camera-8'].geometry} material={darkMat} />
      <mesh geometry={nodes['frontal-camera-9'].geometry} material={darkMat} />
      <mesh geometry={nodes['frontal-camera-10'].geometry} material={darkMat} />
      <mesh geometry={nodes['frontal-camera-1'].geometry} material={darkMat} />
      <mesh geometry={nodes['frontal-camera-2'].geometry} material={darkMat} />
      <mesh geometry={nodes['edge-a'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['edge-b'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['button-2'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['button-3'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['button-4'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['button-6'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['edge-display'].geometry} material={darkMat} />
      <mesh geometry={nodes['button-5-center'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['button-5'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['port-usb-1'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['port-usb-2'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['port-usb-3'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['port-usb-4'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['port-usb-5'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['port-usb-6'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['port-usb-7'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['port-usb-9'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['port-usb-8'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['sepaker-1'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['speaker-2'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['shadow-1'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['shadow-2'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes.back.geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes.screws.geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes['microphones-lower'].geometry} material={materials['iphone-16-pro-001.001']} />
      <mesh geometry={nodes.display.geometry}>
        <meshBasicMaterial map={screenTexture} toneMapped={false} />
      </mesh>
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/iphone16_mockup/iphone-16-pro.glb')

function AnimatedScene({ containerRef, titleRef, cardsRef, imagePath }: { containerRef: React.RefObject<HTMLDivElement>, titleRef: React.RefObject<HTMLDivElement>, cardsRef: React.RefObject<HTMLDivElement>, imagePath?: string }) {
  const groupRef = useRef<THREE.Group>(null);

  useGSAP(() => {
    if (!groupRef.current || !containerRef.current) return;
    
    const isMobile = window.innerWidth < 768;
    const isTablet = window.innerWidth >= 768 && window.innerWidth < 1024;
    
    // Initial position for entering from right
    gsap.set(groupRef.current.position, {
      x: isMobile ? 80 : 150,
      y: 0,
      z: 0
    });

    const endX = isMobile ? 0 : isTablet ? -60 : -120;
    const endY = 0;
    
    // Setup initial position
    // Starting at -Math.PI * 2 - (Math.PI / 4) will make it spin 360+45 degrees and end exactly at 0!
    if (groupRef.current) {
      groupRef.current.rotation.set(0, -Math.PI * 2 - (Math.PI / 4), 0);
    }

    // Create a scroll-driven timeline
    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: containerRef.current,
        start: "top top",
        end: "bottom bottom",
        scrub: 1, // Smooth premium scrub
      }
    });

    // Animate position from top-right to bottom-left
    tl.to(groupRef.current.position, {
      x: endX,
      y: endY,
      z: 0,
      ease: "power1.inOut"
    }, 0);

    // Animate rotation to end perfectly flat and straight (0,0,0)
    tl.to(groupRef.current.rotation, {
      x: 0,
      y: 0.3, // Slightly oriented towards the right
      z: 0,
      ease: "power1.inOut" // Smooth start and end to the rotation
    }, 0);
    
    // Animate title to exit left
    if (titleRef.current) {
      tl.to(titleRef.current, {
        xPercent: -150,
        opacity: 0,
        ease: "none"
      }, 0);
    }
    
    // Animate cards entering from right
    if (cardsRef.current) {
      // Set initial state: far to the right
      gsap.set(cardsRef.current, { opacity: 0, x: 800 });
      
      tl.to(cardsRef.current, {
        x: 0,
        opacity: 1,
        ease: "power2.out",
        duration: 0.9 // Slower, matches the phone's 1.0 duration better
      }, 0.1); // Starts almost immediately, following the phone
    }



  }, { scope: containerRef, dependencies: [] });

  return (
    <>
      <group ref={groupRef}>
        <Resize scale={150}>
          <Center>
            {/* Rotating Math.PI on Y to show the screen first */}
            <Model rotation={[0, Math.PI, 0]} imagePath={imagePath} />
          </Center>
        </Resize>
      </group>
    </>
  );
}

export default function IphoneMockup3D({ imagePath }: { imagePath?: string } = {}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const titleRef = useRef<HTMLDivElement>(null);
  const cardsRef = useRef<HTMLDivElement>(null);

  return (
    <ErrorBoundary fallback={(err) => <div className="text-red-500 p-4 border border-red-500 rounded bg-red-900/20">Error 3D: {err.message}</div>}>
      <div ref={containerRef} className="w-full h-[300vh] relative">
        <div className="sticky top-0 w-full h-screen overflow-hidden">
          <AuroraBackground className="!bg-transparent h-full w-full">
            <div className="absolute inset-0 pointer-events-none flex flex-col justify-center pl-[5%] md:pl-[10%] lg:pl-[12%] pr-[5%] z-10">
              <div ref={titleRef} className="flex flex-col gap-6 max-w-xl md:max-w-2xl">
                <h1 className="text-5xl md:text-7xl lg:text-8xl font-bold text-white max-w-max leading-none">
                   Cos'è<br />
                   <span className="text-[#068b35] whitespace-nowrap">Bussola Verde?</span>
                </h1>
                <p className="text-lg md:text-xl text-neutral-400 font-light leading-relaxed">
                  Un ecosistema digitale che trasforma il parco in un percorso su misura, rendendo il visitatore esploratore attivo.
                </p>
              </div>
            </div>
            
            <div ref={cardsRef} className="absolute right-[2%] md:right-[5%] lg:right-[8%] xl:right-[10%] top-[50%] -translate-y-1/2 w-[95vw] max-w-[320px] md:max-w-none md:w-[55vw] lg:w-[58vw] xl:w-[55vw] z-10 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6 lg:gap-8">
               <HighlightCard animatedBorder={true} title="Interattività" description={["Pannelli digitali e QR accrescono la conoscenza."]} icon={<Compass className="w-6 h-6 text-[#068B35]" />} />
               <HighlightCard animatedBorder={true} title="Percorsi Agili" description={["Itinerari scelti tramite i Totem all'ingresso."]} icon={<ArrowRight className="w-6 h-6 text-[#068B35]" />} />
               <HighlightCard animatedBorder={true} title="Accessibilità" description={["App user-friendly e mappe inclusive per tutti."]} icon={<MapIcon className="w-6 h-6 text-[#068B35]" />} />
            </div>
            <Canvas camera={{ position: [0, 0, 300], fov: 45 }} className="!absolute inset-0 w-full h-full z-0">
              <Suspense fallback={<Html center><div className="text-white text-xl">Caricamento 3D in corso...</div></Html>}>
                <Environment preset="city" />
                <ambientLight intensity={0.5} />
                <directionalLight position={[10, 10, 5]} intensity={1} />
                
                <AnimatedScene containerRef={containerRef} titleRef={titleRef} cardsRef={cardsRef} imagePath={imagePath} />
                
              </Suspense>
            </Canvas>
          </AuroraBackground>
        </div>
      </div>
    </ErrorBoundary>
  )
}
